spring:
  application:
    name: core
  profiles:
    active: dev

app:
  character-Encoding: utf8
  use-unicode: true

# LOGBACK SETIING
#logging:
#  config: classpath:logback.xml

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties.hibernate.format-sql: true
    database:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/Estimate?autoReconnect=true&useUnicode=${app.use-unicode}&characterEncoding=${app.character-Encoding}&useSSL=false
        username: juana
        password: wndksk1!

management.endpoints.web.exposure.include: "*"
